### PR TITLE
Don't close tabs playing audio

### LINKED ISSUE #1: Do not close music tab, no matter what
Music tab should not be closed no matter what.

Even though in newer versions of chrome you can see a speaker icon near the tab that is making music i couldn't find any call to check this behavior per tab. Maybe we can take the decision based on the links (don't close pandora/youtube links?)

### PR DESCRIPTION
**Pull request by walles**
Fixes #1

Look for `audible` here for docs: https://developer.chrome.com/extensions/tabs

### CODE REVIEW

**Comment by vilie** [comment]
+1

**Comment by ccampbell** [comment]
This functionality has been added in version 1.0.0 of the extension. I am doing a slow rollout, but you can manually install it from the [Chrome web store](https://chrome.google.com/webstore/detail/xtab/amddgdnlkmohapieeekfknakgdnpbleb) if you would like to try it.

**Comment by walles** [comment]
I just checked the source code here and I don't see anything about checking for `audible`.

How do you check for whether a tab is playing audio?

**Comment by ccampbell** [comment]
I have decided to develop new versions of xTab in private (at least for the time being). That said, the source code is still viewable from within Chrome. You can search for `.audible` here to see: chrome-extension://amddgdnlkmohapieeekfknakgdnpbleb/dist/xtab.js or you can use something like this: https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin

**Pull request closed without merging**
